In [1]:
!pip install numpy pandas matplotlib scikit-learn


In [3]:
import numpy as np 
a = np.array([7,9,9,2])
print(a)

[7 9 9 2]


In [5]:
import numpy as np 
a = np.array([(7,9,9,2),(7,5,6,3)])
print(a)

[[7 9 9 2]
 [7 5 6 3]]


In [9]:
c = np.array(10)
d = np.linspace(1,5,6)
print(c)
print(d)

10
[1.  1.8 2.6 3.4 4.2 5. ]


In [17]:
a=np.array([5,6,8,9])
b = np.array([(5,8,9,6),(1,2,3,4)])
print("for a:")
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size*a.itemsize)
print(a.size)
print(a.shape)

print("for b:")
print(b.ndim)
print(b.itemsize)
print(b.dtype)
print(b.size*a.itemsize)
print(b.size)
print(b.shape)



for a:
1
4
int32
16
4
(4,)
for b:
2
4
int32
32
8
(2, 4)


In [23]:
b = np.array([(7,9,9,5),(7,2,6,8)])
print(b)
print("AFTER RESHAPING:")
b = b.reshape(4,2)
print(b)

[[7 9 9 5]
 [7 2 6 8]]
AFTER RESHAPING:
[[7 9]
 [9 5]
 [7 2]
 [6 8]]


In [27]:
b = np.array([(7,9,9,2),(16,11,9,6)])
print(b[0,2])
print(b[0:,2])

9
[9 9]


In [29]:
e = np.array([(7,9,9,2,16,11,9,6)])
print(e.min())
print(e.max())
print(e.sum())

2
16
69


In [31]:
a=np.array([5,6,8,9])
b = np.array([(5,8,9,6),(1,2,3,4)])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))
print(np.exp(a))
print(np.log(a))
print(np.log10(a))



[ 6 10 12 10]
[28 10]
[2.23606798 2.44948974 2.82842712 3.        ]
1.5811388300841898
[ 148.4131591   403.42879349 2980.95798704 8103.08392758]
[1.60943791 1.79175947 2.07944154 2.19722458]
[0.69897    0.77815125 0.90308999 0.95424251]


In [39]:
b = np.array([(5,8,9,6),(1,2,3,4)])
f = np.array([(2,8,6,7),(8,3,6,6)])
print(np.vstack((b,f)))
print(" ")
print(np.hstack((b,f)))
print(" ")
print(b.ravel())
print(" ")
print(f.ravel())




[[5 8 9 6]
 [1 2 3 4]
 [2 8 6 7]
 [8 3 6 6]]
 
[[5 8 9 6 2 8 6 7]
 [1 2 3 4 8 3 6 6]]
 
[5 8 9 6 1 2 3 4]
 
[2 8 6 7 8 3 6 6]


In [41]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [57]:
ranges = np.arange(5.6,9.8)
print(ranges)
print(np.linspace(3,6,10))

[5.6 6.6 7.6 8.6 9.6]
[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]


In [61]:
matrix = np.array([[76,34,89],[23,34,45]])
print(matrix+ 2)

[[78 36 91]
 [25 36 47]]


In [69]:
matrix = np.array([[76,34,89],[23,34,45]])
print(matrix*2)
print(matrix/2)
print(matrix.T)
print(matrix[1,])

[[152  68 178]
 [ 46  68  90]]
[[38.  17.  44.5]
 [11.5 17.  22.5]]
[[76 23]
 [34 34]
 [89 45]]
[23 34 45]


In [81]:
full = np.full(10,5)
print(full)
print(" ")
full = np.full((2,2),10)
print(full)
print(" ")
full = np.full((2,2,3),5)
print(full)

[5 5 5 5 5 5 5 5 5 5]
 
[[10 10]
 [10 10]]
 
[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]


In [83]:
pythonlist1 = [[22,56,48,96],[55,22,33,66]]
pythonlist2 = [[21,55,47,95],[55,22,33,66]]
pythonlist1 + pythonlist2


[[22, 56, 48, 96], [55, 22, 33, 66], [21, 55, 47, 95], [55, 22, 33, 66]]

In [98]:
matrix1 = np.array([[4,5,6,2,3],[4,1,2,3,6]])
matrix2 = np.array([[4,8,6,9,2],[8,4,5,2,1]])
print(matrix1 + matrix2)
print(" ")
print(matrix1 - matrix2)
print(" ")
print(matrix1 * matrix2)
print(" ")
print(matrix1 / matrix2)
print(" ")

[[ 8 13 12 11  5]
 [12  5  7  5  7]]
 
[[ 0 -3  0 -7  1]
 [-4 -3 -3  1  5]]
 
[[16 40 36 18  6]
 [32  4 10  6  6]]
 
[[1.         0.625      1.         0.22222222 1.5       ]
 [0.5        0.25       0.4        1.5        6.        ]]
 


In [112]:
marks = np.array([
    [87,85,63],[100,25,48],
    [47,88,66],[100,23,96]
])
print(marks)
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())
print("    ")
print(marks.min(axis=1))
print(marks.max(axis=1))
print(marks.sum(axis=1))
print(marks.mean(axis=1))
print(marks.std(axis=1))

[[ 87  85  63]
 [100  25  48]
 [ 47  88  66]
 [100  23  96]]
23
100
828
69.0
26.792411861072406
    
[63 25 47 23]
[ 87 100  88 100]
[235 173 201 219]
[78.33333333 57.66666667 67.         73.        ]
[10.87300429 31.37231618 16.75310916 35.39303133]


In [118]:

x = np.array([2, 3, 5, 6])
y = np.array([2, 3, 5, 6])
z = np.array([2, 3, 5, 6])
print(np.vstack((x, z)))  
print(np.hstack((x, z)))  # Corrected: Use (x, z) inside parentheses


[[2 3 5 6]
 [2 3 5 6]]
[2 3 5 6 2 3 5 6]


In [120]:
np.append(x,(2,3))

array([2, 3, 5, 6, 2, 3])

In [128]:
new_array = np.array([1,2,3])
x = np.append([[1,2,3],[4,5,6]],[[1,2,3],new_array],axis=0)
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3]])

In [130]:
np.transpose(x)

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [134]:
arr = np.arange(7)
print(arr)
print(arr > 4)

[0 1 2 3 4 5 6]
[False False False False False  True  True]


In [138]:
array = np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
array.shape = (3,4)
print(array.shape)

(3, 4)


In [146]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [168]:
rand_floats = np.random.rand(5)
print("Random Floats:\n", rand_floats)
rand_ints = np.random.randint(5, 20, (5, 5))
print("\nRandom Integers:\n", rand_ints)
letters = ['z', 'g', 'h', 'j', 'i']
rand_choices = np.random.choice(letters, 5, replace=False)
print("\nRandom Choices (Unique):\n", rand_choices)
probabilities = [0.4, 0.3, 0.2, 0.05, 0.05]
rand_choices = np.random.choice(letters, 5, p=probabilities)
print("\nRandom Choices (Weighted):\n", rand_choices)


Random Floats:
 [0.56265669 0.33771724 0.46217409 0.87896691 0.1824402 ]

Random Integers:
 [[19 16 10 13  6]
 [19 11  7  7  6]
 [ 5 18  9 11 19]
 [16 12 12 14  7]
 [ 9 14 15 12  8]]

Random Choices (Unique):
 ['h' 'i' 'z' 'g' 'j']

Random Choices (Weighted):
 ['h' 'h' 'g' 'z' 'j']


In [170]:
array = np.random.randit(10,20,(5,5))
np.save('array_file',array)

AttributeError: module 'numpy.random' has no attribute 'randit'

In [1]:
import pandas as pd
import numpy as np

In [3]:
series1 = pd .Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(series1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [5]:
series2 = pd .Series(np.random.randn(5),index=['a','b','c','d','e'])
print(series2)

a   -2.125864
b    1.141605
c   -1.365164
d    0.770912
e   -3.502042
dtype: float64


In [7]:
dictionary = {'a':1, 'b':2, 'c':3}
print(pd.Series(dictionary))

a    1
b    2
c    3
dtype: int64


In [9]:
#[]-series
#[[]]-dataframe